### ISSUE TITLE
为啥我跑出来的是这个鸭，是我用法有问题吗

### ISSUE THREAD

**Issue by zwx980624** [DanielW10001/C0Autogen#1]
运行python grammar.py out.txt生成了下面这个东西，请问我应该怎么使用才能生成正确的文法呢

{| -> [
{+ -> [
{[] -> [
{| -> [
{+ -> [
<常量说明>
]}
]}
]},
{[] -> [
{| -> [
{+ -> [
<变量说明>
]}
]}
]},
{{} -> [
{| -> [
{+ -> [
<有返回值函数定义>
]},
{+ -> [
<无返回值函数定义>
]}
]}
]},
<主函数>
]}
]}

**Comment by DanielW10001** [comment]
This is the result of `print(program_grammar)`.
To generate a legal program, please use `print(program_grammar.get_random_instance())` instead.
See line 486 of `./grammar.py`.
Please read `README.md` carefully before usage or issueing.
